---
title: "nasapower"
author: "Adam H. Sparks"
output:
  rmarkdown::html_vignette:
    toc: true
vignette: >
  %\VignetteIndexEntry{nasapower}
  %\VignetteEngine{knitr::rmarkdown_notangle}
  %\VignetteEncoding{UTF-8}
  %\VignetteDepends{ratelimitr}
---



## Introduction

_nasapower_ aims to make it quick and easy to automate downloading NASA [POWER](https://power.larc.nasa.gov) global meteorology, surface solar energy and climatology data  data in your R session as a tidy data frame for analysis and use in modelling or other purposes using `get_power()`.
POWER (Prediction Of Worldwide Energy Resource) data are freely available for download through a web interface with a spatial resolution of 0.5 x 0.625 degree latitude and longitude for meteorology and  1 x 1 degree latitude and longitude for solar parameters with various temporal resolutions depending on the POWER parameter and community.

## Using get_power() to fetch POWER data

The `get_power()` function has eight possible arguments and returns a data frame with a metadata header in the current R session.

### Example fetching daily data for a single point

Fetch daily "AG" community temperature, relative humidity and precipitation for January 1985 for Kingsthorpe, Queensland, Australia.


```r
library("nasapower")
daily_single_ag <- get_power(
  community = "ag",
  lonlat = c(151.81, -27.48),
  pars = c("RH2M", "T2M", "PRECTOTCORR"),
  dates = c("1985-01-01", "1985-01-31"),
  temporal_api = "daily"
)

daily_single_ag
#> NASA/POWER CERES/MERRA2 Native Resolution Daily Data  
#>  Dates (month/day/year): 01/01/1985 through 01/31/1985  
#>  Location: Latitude  -27.48   Longitude 151.81  
#>  Elevation from MERRA-2: Average for 0.5 x 0.625 degree lat/lon region = 442.77 meters 
#>  Value for missing model data cannot be computed or out of model availability range: NA  
#>  Parameter(s):  
#>  
#>  Parameters: 
#>  RH2M            MERRA-2 Relative Humidity at 2 Meters (%) ;
#>  T2M             MERRA-2 Temperature at 2 Meters (C) ;
#>  PRECTOTCORR     MERRA-2 Precipitation Corrected (mm/day)  
#>  
#> # A tibble: 31 × 10
#>      LON   LAT  YEAR    MM    DD   DOY YYYYMMDD    RH2M   T2M
#>    <dbl> <dbl> <dbl> <int> <int> <int> <date>     <dbl> <dbl>
#>  1  152. -27.5  1985     1     1     1 1985-01-01  54.7  24.9
#>  2  152. -27.5  1985     1     2     2 1985-01-02  42.1  28.6
#>  3  152. -27.5  1985     1     3     3 1985-01-03  43.4  27.4
#>  4  152. -27.5  1985     1     4     4 1985-01-04  48.9  24.3
#>  5  152. -27.5  1985     1     5     5 1985-01-05  55.3  26.5
#>  6  152. -27.5  1985     1     6     6 1985-01-06  60.2  27.0
#>  7  152. -27.5  1985     1     7     7 1985-01-07  63.1  27.2
#>  8  152. -27.5  1985     1     8     8 1985-01-08  70.6  24.9
#>  9  152. -27.5  1985     1     9     9 1985-01-09  60    26.1
#> 10  152. -27.5  1985     1    10    10 1985-01-10  45.2  27.0
#> # … with 21 more rows, and 1 more variable: PRECTOTCORR <dbl>
```

### Example fetching daily data for an area

Fetch daily "ag" community relative humidity and temperature for south east Queensland region.


```r
daily_region_ag <- get_power(
  community = "ag",
  lonlat = c(150.5, -28.5 , 153.5, -25.5),
  pars = c("RH2M", "T2M"),
  dates = c("1985-01-01", "1985-01-02"),
  temporal_api = "daily"
)

daily_region_ag
#> NASA/POWER CERES/MERRA2 Native Resolution Daily Data  
#>  Dates (month/day/year): 01/01/1985 through 01/02/1985  
#>  Location: Regional  
#>  Elevation from MERRA-2: Average for 0.5 x 0.625 degree lat/lon region = na meters 
#>  Value for missing model data cannot be computed or out of model availability range: NA  
#>  Parameter(s):  
#>  
#>  Parameters: 
#>  RH2M     MERRA-2 Relative Humidity at 2 Meters (%) ;
#>  T2M      MERRA-2 Temperature at 2 Meters (C)  
#>  
#> # A tibble: 72 × 9
#>      LAT   LON  YEAR    MM    DD   DOY YYYYMMDD    RH2M   T2M
#>    <dbl> <dbl> <dbl> <int> <int> <int> <date>     <dbl> <dbl>
#>  1 -28.2  151.  1985     1     1     1 1985-01-01  43.6  26.5
#>  2 -28.2  151.  1985     1     1     1 1985-01-01  44.4  25.8
#>  3 -28.2  152.  1985     1     1     1 1985-01-01  52.6  24.0
#>  4 -28.2  152.  1985     1     1     1 1985-01-01  57.7  23.9
#>  5 -28.2  153.  1985     1     1     1 1985-01-01  61.4  24.9
#>  6 -28.2  153.  1985     1     1     1 1985-01-01  66.1  26.0
#>  7 -27.8  151.  1985     1     1     1 1985-01-01  45.8  26.5
#>  8 -27.8  151.  1985     1     1     1 1985-01-01  47.9  26.0
#>  9 -27.8  152.  1985     1     1     1 1985-01-01  53.4  24.8
#> 10 -27.8  152.  1985     1     1     1 1985-01-01  56.7  25.1
#> # … with 62 more rows
```

### Example fetching interannual data for an area

Fetch interannual solar cooking parameters for south east Queensland region.


```r
interannual_re <- get_power(
  community = "re",
  lonlat = c(150.5, -28.5 , 153.5, -25.5),
  dates = c("1984", "1985"),
  temporal_api = "monthly",
  pars = c("CLRSKY_SFC_SW_DWN",
           "ALLSKY_SFC_SW_DWN")
)

interannual_re
#> NASA/POWER CERES/MERRA2 Native Resolution Monthly and Annual  
#>  Dates (month/day/year): 01/01/1984 through 12/31/1985  
#>  Location: Regional  
#>  Elevation from MERRA-2: Average for 0.5 x 0.625 degree lat/lon region = na meters 
#>  Value for missing model data cannot be computed or out of model availability range: NA  
#>  Parameter(s):  
#>  
#>  Parameters: 
#>  ALLSKY_SFC_SW_DWN     CERES SYN1deg All Sky Surface Shortwave Downward Irradiance (kW-hr/m^2/day) ;
#>  CLRSKY_SFC_SW_DWN     CERES SYN1deg Clear Sky Surface Shortwave Downward Irradiance (kW-hr/m^2/day)  
#>  
#> # A tibble: 144 × 17
#>    PARAMETER    YEAR   LAT   LON   JAN   FEB   MAR   APR   MAY
#>    <chr>       <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
#>  1 ALLSKY_SFC…  1984 -25.8  151.  6.01  6.49  5.79  4.67  4.12
#>  2 ALLSKY_SFC…  1984 -25.8  151.  5.92  5.97  5.64  4.37  4.01
#>  3 ALLSKY_SFC…  1984 -25.8  152.  5.92  5.97  5.64  4.37  4.01
#>  4 ALLSKY_SFC…  1984 -25.8  152.  5.96  5.85  5.56  4.26  3.92
#>  5 ALLSKY_SFC…  1984 -25.8  153.  5.96  5.85  5.56  4.26  3.92
#>  6 ALLSKY_SFC…  1984 -25.8  153.  6.23  6.05  5.88  4.26  3.81
#>  7 ALLSKY_SFC…  1984 -26.2  151.  5.97  6.65  6     4.66  4.02
#>  8 ALLSKY_SFC…  1984 -26.2  151.  6     6.38  5.71  4.38  4.01
#>  9 ALLSKY_SFC…  1984 -26.2  152.  6     6.38  5.71  4.38  4.01
#> 10 ALLSKY_SFC…  1984 -26.2  152.  5.75  5.96  5.37  4.13  3.8 
#> # … with 134 more rows, and 8 more variables: JUN <dbl>,
#> #   JUL <dbl>, AUG <dbl>, SEP <dbl>, OCT <dbl>, NOV <dbl>,
#> #   DEC <dbl>, ANN <dbl>
```

### Example fetching climatology data

Climatology data can be retrieved for point or regional areas as demonstrated previously.
Change the `temporal_api` value to "climatology" to get these data.

Fetch "ag" climatology for temperature and relative humidity for Kingsthorpe, Queensland, Australia.


```r
climatology_ag <- get_power(
  community = "ag",
  pars = c("T2M", "RH2M"),
  lonlat = c(151.81, -27.48),
  temporal_api = "climatology"
)

climatology_ag
#> NASA/POWER CERES/MERRA2 Native Resolution Climatology Climatologies  
#>  30-year Meteorological and Solar Monthly & Annual Climatologies (January 1990 - December 2019)  
#>  Location: Latitude  -27.48   Longitude 151.81  
#>  Elevation from MERRA-2: Average for 0.5 x 0.625 degree lat/lon region = 442.77 meters 
#>  Value for missing model data cannot be computed or out of model availability range: NA  
#>  Parameter(s):  
#>  
#>  Parameters: 
#>  T2M      MERRA-2 Temperature at 2 Meters (C) ;
#>  RH2M     MERRA-2 Relative Humidity at 2 Meters (%)  
#>  
#> # A tibble: 2 × 16
#>     LON   LAT PARAMETER   JAN   FEB   MAR   APR   MAY   JUN
#>   <dbl> <dbl> <chr>     <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
#> 1  152. -27.5 T2M        24.3  23.5  21.8  18.7  15.1  12.2
#> 2  152. -27.5 RH2M       65.5  70.1  70.4  70.1  71.8  75.5
#> # … with 7 more variables: JUL <dbl>, AUG <dbl>, SEP <dbl>,
#> #   OCT <dbl>, NOV <dbl>, DEC <dbl>, ANN <dbl>
```

_Note_ the associated metadata in the data frame header are not saved if the data are exported to a file format other than an R data format, _e.g._, .Rdata, .rda or .rds.

## Interrogating the API for available parameters

The POWER API offers functionality to get detailed information on any parameter offered or all parameters that are offered for a given community and temporal API.
This can be used to find available parameter names and definitions for each community and temporal API.

Fetch the complete available information for the temperature at 2 metres above the Earth's surface, T2M.


```r
query_parameters(par = "T2M")
#> $T2M
#> $T2M$temporal
#> $T2M$temporal$HOURLY
#> $T2M$temporal$HOURLY$name
#> [1] "Temperature at 2 Meters"
#> 
#> $T2M$temporal$HOURLY$definition
#> [1] "The average air (dry bulb) temperature at 2 meters above the surface of the earth."
#> 
#> $T2M$temporal$HOURLY$communities
#> [1] "AG" "RE" "SB"
#> 
#> $T2M$temporal$HOURLY$calculated
#> [1] FALSE
#> 
#> 
#> $T2M$temporal$DAILY
#> $T2M$temporal$DAILY$name
#> [1] "Temperature at 2 Meters"
#> 
#> $T2M$temporal$DAILY$definition
#> [1] "The average air (dry bulb) temperature at 2 meters above the surface of the earth."
#> 
#> $T2M$temporal$DAILY$communities
#> [1] "AG" "RE" "SB"
#> 
#> $T2M$temporal$DAILY$calculated
#> [1] FALSE
#> 
#> 
#> $T2M$temporal$MONTHLY
#> $T2M$temporal$MONTHLY$name
#> [1] "Temperature at 2 Meters"
#> 
#> $T2M$temporal$MONTHLY$definition
#> [1] "The average air (dry bulb) temperature at 2 meters above the surface of the earth."
#> 
#> $T2M$temporal$MONTHLY$communities
#> [1] "AG" "RE" "SB"
#> 
#> $T2M$temporal$MONTHLY$calculated
#> [1] FALSE
#> 
#> 
#> $T2M$temporal$CLIMATOLOGY
#> $T2M$temporal$CLIMATOLOGY$name
#> [1] "Temperature at 2 Meters"
#> 
#> $T2M$temporal$CLIMATOLOGY$definition
#> [1] "The average air (dry bulb) temperature at 2 meters above the surface of the earth."
#> 
#> $T2M$temporal$CLIMATOLOGY$communities
#> [1] "AG" "RE" "SB"
#> 
#> $T2M$temporal$CLIMATOLOGY$calculated
#> [1] FALSE
#> 
#> 
#> 
#> $T2M$type
#> [1] "METEOROLOGY"
```

Fetch complete temporal and community specific attribute information for "T2M" in the "ag" community for the "hourly" temporal API.


```r
query_parameters(par = "T2M",
                 community = "ag",
                 temporal_api = "hourly")
#> $T2M
#> $T2M$type
#> [1] "METEOROLOGY"
#> 
#> $T2M$temporal
#> [1] "HOURLY"
#> 
#> $T2M$source
#> [1] "MERRA2"
#> 
#> $T2M$community
#> [1] "AG"
#> 
#> $T2M$calculated
#> [1] FALSE
#> 
#> $T2M$inputs
#> NULL
#> 
#> $T2M$units
#> [1] "C"
#> 
#> $T2M$name
#> [1] "Temperature at 2 Meters"
#> 
#> $T2M$definition
#> [1] "The average air (dry bulb) temperature at 2 meters above the surface of the earth."
```

Fetch complete temporal and community specific attribute information for all parameters in the "ag" community for the "hourly" temporal API.


```r
query_parameters(community = "ag",
                 temporal_api = "hourly")
#> $PRECSNOLAND
#> $PRECSNOLAND$type
#> [1] "METEOROLOGY"
#> 
#> $PRECSNOLAND$temporal
#> [1] "HOURLY"
#> 
#> $PRECSNOLAND$source
#> [1] "MERRA2"
#> 
#> $PRECSNOLAND$community
#> [1] "AG"
#> 
#> $PRECSNOLAND$calculated
#> [1] FALSE
#> 
#> $PRECSNOLAND$inputs
#> NULL
#> 
#> $PRECSNOLAND$units
#> [1] "mm/hour"
#> 
#> $PRECSNOLAND$name
#> [1] "Snow Precipitation Land"
#> 
#> $PRECSNOLAND$definition
#> [1] "The snow precipitation only over land at the surface of the earth."
#> 
#> 
#> $PRECTOTCORR
#> $PRECTOTCORR$type
#> [1] "METEOROLOGY"
#> 
#> $PRECTOTCORR$temporal
#> [1] "HOURLY"
#> 
#> $PRECTOTCORR$source
#> [1] "MERRA2"
#> 
#> $PRECTOTCORR$community
#> [1] "AG"
#> 
#> $PRECTOTCORR$calculated
#> [1] FALSE
#> 
#> $PRECTOTCORR$inputs
#> NULL
#> 
#> $PRECTOTCORR$units
#> [1] "mm/hour"
#> 
#> $PRECTOTCORR$name
#> [1] "Precipitation Corrected"
#> 
#> $PRECTOTCORR$definition
#> [1] "The bias corrected average of total precipitation at the surface of the earth in water mass (includes water content in snow)."
#> 
#> 
#> $PS
#> $PS$type
#> [1] "METEOROLOGY"
#> 
#> $PS$temporal
#> [1] "HOURLY"
#> 
#> $PS$source
#> [1] "MERRA2"
#> 
#> $PS$community
#> [1] "AG"
#> 
#> $PS$calculated
#> [1] FALSE
#> 
#> $PS$inputs
#> NULL
#> 
#> $PS$units
#> [1] "kPa"
#> 
#> $PS$name
#> [1] "Surface Pressure"
#> 
#> $PS$definition
#> [1] "The average of surface pressure at the surface of the earth."
#> 
#> 
#> $QV10M
#> $QV10M$type
#> [1] "METEOROLOGY"
#> 
#> $QV10M$temporal
#> [1] "HOURLY"
#> 
#> $QV10M$source
#> [1] "MERRA2"
#> 
#> $QV10M$community
#> [1] "AG"
#> 
#> $QV10M$calculated
#> [1] FALSE
#> 
#> $QV10M$inputs
#> NULL
#> 
#> $QV10M$units
#> [1] "g/kg"
#> 
#> $QV10M$name
#> [1] "Specific Humidity at 10 Meters"
#> 
#> $QV10M$definition
#> [1] "The ratio of the mass of water vapor to the total mass of air at 10 meters (kg water/kg total air)."
#> 
#> 
#> $QV2M
#> $QV2M$type
#> [1] "METEOROLOGY"
#> 
#> $QV2M$temporal
#> [1] "HOURLY"
#> 
#> $QV2M$source
#> [1] "MERRA2"
#> 
#> $QV2M$community
#> [1] "AG"
#> 
#> $QV2M$calculated
#> [1] FALSE
#> 
#> $QV2M$inputs
#> NULL
#> 
#> $QV2M$units
#> [1] "g/kg"
#> 
#> $QV2M$name
#> [1] "Specific Humidity at 2 Meters"
#> 
#> $QV2M$definition
#> [1] "The ratio of the mass of water vapor to the total mass of air at 2 meters (kg water/kg total air)."
#> 
#> 
#> $RH2M
#> $RH2M$type
#> [1] "METEOROLOGY"
#> 
#> $RH2M$temporal
#> [1] "HOURLY"
#> 
#> $RH2M$source
#> [1] "MERRA2"
#> 
#> $RH2M$community
#> [1] "AG"
#> 
#> $RH2M$calculated
#> [1] FALSE
#> 
#> $RH2M$inputs
#> [1] "T2M"  "PS"   "QV2M"
#> 
#> $RH2M$units
#> [1] "%"
#> 
#> $RH2M$name
#> [1] "Relative Humidity at 2 Meters"
#> 
#> $RH2M$definition
#> [1] "The ratio of actual partial pressure of water vapor to the partial pressure at saturation, expressed in percent."
#> 
#> 
#> $SNODP
#> $SNODP$type
#> [1] "METEOROLOGY"
#> 
#> $SNODP$temporal
#> [1] "HOURLY"
#> 
#> $SNODP$source
#> [1] "MERRA2"
#> 
#> $SNODP$community
#> [1] "AG"
#> 
#> $SNODP$calculated
#> [1] FALSE
#> 
#> $SNODP$inputs
#> NULL
#> 
#> $SNODP$units
#> [1] "cm"
#> 
#> $SNODP$name
#> [1] "Snow Depth"
#> 
#> $SNODP$definition
#> [1] "The snow depth on land at surface of the earth."
#> 
#> 
#> $T2M
#> $T2M$type
#> [1] "METEOROLOGY"
#> 
#> $T2M$temporal
#> [1] "HOURLY"
#> 
#> $T2M$source
#> [1] "MERRA2"
#> 
#> $T2M$community
#> [1] "AG"
#> 
#> $T2M$calculated
#> [1] FALSE
#> 
#> $T2M$inputs
#> NULL
#> 
#> $T2M$units
#> [1] "C"
#> 
#> $T2M$name
#> [1] "Temperature at 2 Meters"
#> 
#> $T2M$definition
#> [1] "The average air (dry bulb) temperature at 2 meters above the surface of the earth."
#> 
#> 
#> $TS
#> $TS$type
#> [1] "METEOROLOGY"
#> 
#> $TS$temporal
#> [1] "HOURLY"
#> 
#> $TS$source
#> [1] "MERRA2"
#> 
#> $TS$community
#> [1] "AG"
#> 
#> $TS$calculated
#> [1] FALSE
#> 
#> $TS$inputs
#> NULL
#> 
#> $TS$units
#> [1] "C"
#> 
#> $TS$name
#> [1] "Earth Skin Temperature"
#> 
#> $TS$definition
#> [1] "The average temperature at the earth's surface."
#> 
#> 
#> $U10M
#> $U10M$type
#> [1] "METEOROLOGY"
#> 
#> $U10M$temporal
#> [1] "HOURLY"
#> 
#> $U10M$source
#> [1] "MERRA2"
#> 
#> $U10M$community
#> [1] "AG"
#> 
#> $U10M$calculated
#> [1] FALSE
#> 
#> $U10M$inputs
#> NULL
#> 
#> $U10M$units
#> [1] "m/s"
#> 
#> $U10M$name
#> [1] "Eastward Wind at 10 Meters"
#> 
#> $U10M$definition
#> [1] "The estimate of the eastward wind average speed for winds blowing 10 meters above the surface of the earth."
#> 
#> 
#> $U2M
#> $U2M$type
#> [1] "METEOROLOGY"
#> 
#> $U2M$temporal
#> [1] "HOURLY"
#> 
#> $U2M$source
#> [1] "MERRA2"
#> 
#> $U2M$community
#> [1] "AG"
#> 
#> $U2M$calculated
#> [1] FALSE
#> 
#> $U2M$inputs
#> NULL
#> 
#> $U2M$units
#> [1] "m/s"
#> 
#> $U2M$name
#> [1] "Eastward Wind at 2 Meters"
#> 
#> $U2M$definition
#> [1] "The estimate of the eastward wind average speed for winds blowing 2 meters above the surface of the earth."
#> 
#> 
#> $U50M
#> $U50M$type
#> [1] "METEOROLOGY"
#> 
#> $U50M$temporal
#> [1] "HOURLY"
#> 
#> $U50M$source
#> [1] "MERRA2"
#> 
#> $U50M$community
#> [1] "AG"
#> 
#> $U50M$calculated
#> [1] FALSE
#> 
#> $U50M$inputs
#> NULL
#> 
#> $U50M$units
#> [1] "m/s"
#> 
#> $U50M$name
#> [1] "Eastward Wind at 50 Meters"
#> 
#> $U50M$definition
#> [1] "The estimate of the eastward wind average speed for winds blowing 50 meters above the surface of the earth."
#> 
#> 
#> $V10M
#> $V10M$type
#> [1] "METEOROLOGY"
#> 
#> $V10M$temporal
#> [1] "HOURLY"
#> 
#> $V10M$source
#> [1] "MERRA2"
#> 
#> $V10M$community
#> [1] "AG"
#> 
#> $V10M$calculated
#> [1] FALSE
#> 
#> $V10M$inputs
#> NULL
#> 
#> $V10M$units
#> [1] "m/s"
#> 
#> $V10M$name
#> [1] "Northward Wind at 10 Meters"
#> 
#> $V10M$definition
#> [1] "The estimate of the northward wind average speed for winds blowing 10 meters above the surface of the earth."
#> 
#> 
#> $V2M
#> $V2M$type
#> [1] "METEOROLOGY"
#> 
#> $V2M$temporal
#> [1] "HOURLY"
#> 
#> $V2M$source
#> [1] "MERRA2"
#> 
#> $V2M$community
#> [1] "AG"
#> 
#> $V2M$calculated
#> [1] FALSE
#> 
#> $V2M$inputs
#> NULL
#> 
#> $V2M$units
#> [1] "m/s"
#> 
#> $V2M$name
#> [1] "Northward Wind at 2 Meters"
#> 
#> $V2M$definition
#> [1] "The estimate of the northward wind average speed for winds blowing 2 meters above the surface of the earth."
#> 
#> 
#> $V50M
#> $V50M$type
#> [1] "METEOROLOGY"
#> 
#> $V50M$temporal
#> [1] "HOURLY"
#> 
#> $V50M$source
#> [1] "MERRA2"
#> 
#> $V50M$community
#> [1] "AG"
#> 
#> $V50M$calculated
#> [1] FALSE
#> 
#> $V50M$inputs
#> NULL
#> 
#> $V50M$units
#> [1] "m/s"
#> 
#> $V50M$name
#> [1] "Northward Wind at 50 Meters"
#> 
#> $V50M$definition
#> [1] "The estimate of the northward wind average speed for winds blowing 50 meters above the surface of the earth."
#> 
#> 
#> $PSC
#> $PSC$type
#> [1] "METEOROLOGY"
#> 
#> $PSC$temporal
#> [1] "HOURLY"
#> 
#> $PSC$source
#> [1] "POWER"
#> 
#> $PSC$community
#> [1] "AG"
#> 
#> $PSC$calculated
#> [1] TRUE
#> 
#> $PSC$inputs
#> [1] "PS"  "T2M"
#> 
#> $PSC$units
#> [1] "kPa"
#> 
#> $PSC$name
#> [1] "Corrected Atmospheric Pressure (Adjusted For Site Elevation)"
#> 
#> $PSC$definition
#> [1] "Atmospheric pressure associated with the MERRA-2 grid has been adjusted based upon the difference between the elevation of an underlying surface site and the average elevation of the MERRA-2 grid cell."
#> 
#> 
#> $T2MDEW
#> $T2MDEW$type
#> [1] "METEOROLOGY"
#> 
#> $T2MDEW$temporal
#> [1] "HOURLY"
#> 
#> $T2MDEW$source
#> [1] "POWER"
#> 
#> $T2MDEW$community
#> [1] "AG"
#> 
#> $T2MDEW$calculated
#> [1] FALSE
#> 
#> $T2MDEW$inputs
#> [1] "T2M"  "RH2M"
#> 
#> $T2MDEW$units
#> [1] "C"
#> 
#> $T2MDEW$name
#> [1] "Dew/Frost Point at 2 Meters"
#> 
#> $T2MDEW$definition
#> [1] "The dew/frost point temperature at 2 meters above the surface of the earth."
#> 
#> 
#> $T2MWET
#> $T2MWET$type
#> [1] "METEOROLOGY"
#> 
#> $T2MWET$temporal
#> [1] "HOURLY"
#> 
#> $T2MWET$source
#> [1] "POWER"
#> 
#> $T2MWET$community
#> [1] "AG"
#> 
#> $T2MWET$calculated
#> [1] FALSE
#> 
#> $T2MWET$inputs
#> [1] "PS"     "T2M"    "T2MDEW"
#> 
#> $T2MWET$units
#> [1] "C"
#> 
#> $T2MWET$name
#> [1] "Wet Bulb Temperature at 2 Meters"
#> 
#> $T2MWET$definition
#> [1] "The adiabatic saturation temperature which can be measured by a thermometer covered in a water-soaked cloth over which air is passed at 2 meters above the surface of the earth."
#> 
#> 
#> $WD10M
#> $WD10M$type
#> [1] "METEOROLOGY"
#> 
#> $WD10M$temporal
#> [1] "HOURLY"
#> 
#> $WD10M$source
#> [1] "POWER"
#> 
#> $WD10M$community
#> [1] "AG"
#> 
#> $WD10M$calculated
#> [1] TRUE
#> 
#> $WD10M$inputs
#> [1] "U10M" "V10M"
#> 
#> $WD10M$units
#> [1] "Degrees"
#> 
#> $WD10M$name
#> [1] "Wind Direction at 10 Meters"
#> 
#> $WD10M$definition
#> [1] "The average of the wind direction at 10 meters above the surface of the earth."
#> 
#> 
#> $WD2M
#> $WD2M$type
#> [1] "METEOROLOGY"
#> 
#> $WD2M$temporal
#> [1] "HOURLY"
#> 
#> $WD2M$source
#> [1] "POWER"
#> 
#> $WD2M$community
#> [1] "AG"
#> 
#> $WD2M$calculated
#> [1] TRUE
#> 
#> $WD2M$inputs
#> [1] "U2M" "V2M"
#> 
#> $WD2M$units
#> [1] "Degrees"
#> 
#> $WD2M$name
#> [1] "Wind Direction at 2 Meters"
#> 
#> $WD2M$definition
#> [1] "The average of the wind direction at 2 meters above the surface of the earth."
#> 
#> 
#> $WD50M
#> $WD50M$type
#> [1] "METEOROLOGY"
#> 
#> $WD50M$temporal
#> [1] "HOURLY"
#> 
#> $WD50M$source
#> [1] "POWER"
#> 
#> $WD50M$community
#> [1] "AG"
#> 
#> $WD50M$calculated
#> [1] TRUE
#> 
#> $WD50M$inputs
#> [1] "U50M" "V50M"
#> 
#> $WD50M$units
#> [1] "Degrees"
#> 
#> $WD50M$name
#> [1] "Wind Direction at 50 Meters"
#> 
#> $WD50M$definition
#> [1] "The average of the wind direction at 50 meters above the surface of the earth."
#> 
#> 
#> $WS10M
#> $WS10M$type
#> [1] "METEOROLOGY"
#> 
#> $WS10M$temporal
#> [1] "HOURLY"
#> 
#> $WS10M$source
#> [1] "POWER"
#> 
#> $WS10M$community
#> [1] "AG"
#> 
#> $WS10M$calculated
#> [1] TRUE
#> 
#> $WS10M$inputs
#> [1] "U10M" "V10M"
#> 
#> $WS10M$units
#> [1] "m/s"
#> 
#> $WS10M$name
#> [1] "Wind Speed at 10 Meters"
#> 
#> $WS10M$definition
#> [1] "The average of wind speed at 10 meters above the surface of the earth."
#> 
#> 
#> $WS2M
#> $WS2M$type
#> [1] "METEOROLOGY"
#> 
#> $WS2M$temporal
#> [1] "HOURLY"
#> 
#> $WS2M$source
#> [1] "POWER"
#> 
#> $WS2M$community
#> [1] "AG"
#> 
#> $WS2M$calculated
#> [1] TRUE
#> 
#> $WS2M$inputs
#> [1] "U2M" "V2M"
#> 
#> $WS2M$units
#> [1] "m/s"
#> 
#> $WS2M$name
#> [1] "Wind Speed at 2 Meters"
#> 
#> $WS2M$definition
#> [1] "The average of wind speed at 2 meters above the surface of the earth."
#> 
#> 
#> $WS50M
#> $WS50M$type
#> [1] "METEOROLOGY"
#> 
#> $WS50M$temporal
#> [1] "HOURLY"
#> 
#> $WS50M$source
#> [1] "POWER"
#> 
#> $WS50M$community
#> [1] "AG"
#> 
#> $WS50M$calculated
#> [1] TRUE
#> 
#> $WS50M$inputs
#> [1] "U50M" "V50M"
#> 
#> $WS50M$units
#> [1] "m/s"
#> 
#> $WS50M$name
#> [1] "Wind Speed at 50 Meters"
#> 
#> $WS50M$definition
#> [1] "The average of wind speed at 50 meters above the surface of the earth."
#> 
#> 
#> $WSC
#> $WSC$type
#> [1] "METEOROLOGY"
#> 
#> $WSC$temporal
#> [1] "HOURLY"
#> 
#> $WSC$source
#> [1] "POWER"
#> 
#> $WSC$community
#> [1] "AG"
#> 
#> $WSC$calculated
#> [1] TRUE
#> 
#> $WSC$inputs
#> [1] "WS10M" "WS50M"
#> 
#> $WSC$units
#> [1] "m/s"
#> 
#> $WSC$name
#> [1] "Corrected Wind Speed (Adjusted For Elevation)"
#> 
#> $WSC$definition
#> [1] "Wind speed associated with the MERRA-2 grid adjusted using the Gipe Power Law and the elevation difference between the average elevation of the grid cell and the elevation of the underlying surface."
#> 
#> 
#> $ALLSKY_SFC_LW_DWN
#> $ALLSKY_SFC_LW_DWN$type
#> [1] "RADIATION"
#> 
#> $ALLSKY_SFC_LW_DWN$temporal
#> [1] "HOURLY"
#> 
#> $ALLSKY_SFC_LW_DWN$source
#> [1] "CERES"
#> 
#> $ALLSKY_SFC_LW_DWN$community
#> [1] "AG"
#> 
#> $ALLSKY_SFC_LW_DWN$calculated
#> [1] FALSE
#> 
#> $ALLSKY_SFC_LW_DWN$inputs
#> NULL
#> 
#> $ALLSKY_SFC_LW_DWN$units
#> [1] "W/m^2"
#> 
#> $ALLSKY_SFC_LW_DWN$name
#> [1] "All Sky Surface Longwave Downward Irradiance"
#> 
#> $ALLSKY_SFC_LW_DWN$definition
#> [1] "The downward thermal infrared irradiance under all sky conditions reaching a horizontal plane the surface of the earth. Also known as Horizontal Infrared Radiation Intensity from Sky."
#> 
#> 
#> $ALLSKY_SFC_SW_DIFF
#> $ALLSKY_SFC_SW_DIFF$type
#> [1] "RADIATION"
#> 
#> $ALLSKY_SFC_SW_DIFF$temporal
#> [1] "HOURLY"
#> 
#> $ALLSKY_SFC_SW_DIFF$source
#> [1] "CERES"
#> 
#> $ALLSKY_SFC_SW_DIFF$community
#> [1] "AG"
#> 
#> $ALLSKY_SFC_SW_DIFF$calculated
#> [1] FALSE
#> 
#> $ALLSKY_SFC_SW_DIFF$inputs
#> NULL
#> 
#> $ALLSKY_SFC_SW_DIFF$units
#> [1] "MJ/hr"
#> 
#> $ALLSKY_SFC_SW_DIFF$name
#> [1] "All Sky Surface Shortwave Diffuse Irradiance"
#> 
#> $ALLSKY_SFC_SW_DIFF$definition
#> [1] "The diffuse (light energy scattered out of the direction of the sun) solar irradiance incident on a horizontal plane at the surface of the earth under all sky conditions."
#> 
#> 
#> $ALLSKY_SFC_SW_DWN
#> $ALLSKY_SFC_SW_DWN$type
#> [1] "RADIATION"
#> 
#> $ALLSKY_SFC_SW_DWN$temporal
#> [1] "HOURLY"
#> 
#> $ALLSKY_SFC_SW_DWN$source
#> [1] "CERES"
#> 
#> $ALLSKY_SFC_SW_DWN$community
#> [1] "AG"
#> 
#> $ALLSKY_SFC_SW_DWN$calculated
#> [1] FALSE
#> 
#> $ALLSKY_SFC_SW_DWN$inputs
#> NULL
#> 
#> $ALLSKY_SFC_SW_DWN$units
#> [1] "MJ/hr"
#> 
#> $ALLSKY_SFC_SW_DWN$name
#> [1] "All Sky Surface Shortwave Downward Irradiance"
#> 
#> $ALLSKY_SFC_SW_DWN$definition
#> [1] "The total solar irradiance incident (direct plus diffuse) on a horizontal plane at the surface of the earth under all sky conditions. An alternative term for the total solar irradiance is the \"Global Horizontal Irradiance\" or GHI."
#> 
#> 
#> $ALLSKY_SFC_UV_INDEX
#> $ALLSKY_SFC_UV_INDEX$type
#> [1] "RADIATION"
#> 
#> $ALLSKY_SFC_UV_INDEX$temporal
#> [1] "HOURLY"
#> 
#> $ALLSKY_SFC_UV_INDEX$source
#> [1] "CERES"
#> 
#> $ALLSKY_SFC_UV_INDEX$community
#> [1] "AG"
#> 
#> $ALLSKY_SFC_UV_INDEX$calculated
#> [1] FALSE
#> 
#> $ALLSKY_SFC_UV_INDEX$inputs
#> NULL
#> 
#> $ALLSKY_SFC_UV_INDEX$units
#> [1] "dimensionless"
#> 
#> $ALLSKY_SFC_UV_INDEX$name
#> [1] "All Sky Surface UV Index"
#> 
#> $ALLSKY_SFC_UV_INDEX$definition
#> [1] "The ultraviolet radiation exposure index."
#> 
#> 
#> $ALLSKY_SFC_UVA
#> $ALLSKY_SFC_UVA$type
#> [1] "RADIATION"
#> 
#> $ALLSKY_SFC_UVA$temporal
#> [1] "HOURLY"
#> 
#> $ALLSKY_SFC_UVA$source
#> [1] "CERES"
#> 
#> $ALLSKY_SFC_UVA$community
#> [1] "AG"
#> 
#> $ALLSKY_SFC_UVA$calculated
#> [1] FALSE
#> 
#> $ALLSKY_SFC_UVA$inputs
#> NULL
#> 
#> $ALLSKY_SFC_UVA$units
#> [1] "W/m^2"
#> 
#> $ALLSKY_SFC_UVA$name
#> [1] "All Sky Surface UVA Irradiance"
#> 
#> $ALLSKY_SFC_UVA$definition
#> [1] "The ultraviolet A (UVA 315nm-400nm) irradiance under all sky conditions."
#> 
#> 
#> $ALLSKY_SFC_UVB
#> $ALLSKY_SFC_UVB$type
#> [1] "RADIATION"
#> 
#> $ALLSKY_SFC_UVB$temporal
#> [1] "HOURLY"
#> 
#> $ALLSKY_SFC_UVB$source
#> [1] "CERES"
#> 
#> $ALLSKY_SFC_UVB$community
#> [1] "AG"
#> 
#> $ALLSKY_SFC_UVB$calculated
#> [1] FALSE
#> 
#> $ALLSKY_SFC_UVB$inputs
#> NULL
#> 
#> $ALLSKY_SFC_UVB$units
#> [1] "W/m^2"
#> 
#> $ALLSKY_SFC_UVB$name
#> [1] "All Sky Surface UVB Irradiance"
#> 
#> $ALLSKY_SFC_UVB$definition
#> [1] "The ultraviolet B (UVB 280nm-315nm) irradiance under all sky conditions."
#> 
#> 
#> $AOD_55
#> $AOD_55$type
#> [1] "RADIATION"
#> 
#> $AOD_55$temporal
#> [1] "HOURLY"
#> 
#> $AOD_55$source
#> [1] "CERES"
#> 
#> $AOD_55$community
#> [1] "AG"
#> 
#> $AOD_55$calculated
#> [1] FALSE
#> 
#> $AOD_55$inputs
#> NULL
#> 
#> $AOD_55$units
#> [1] "dimensionless"
#> 
#> $AOD_55$name
#> [1] "Aerosol Optical Depth 55"
#> 
#> $AOD_55$definition
#> [1] "The optical thickness at 0.55 um measured vertically; the component of the atmosphere to quantify the removal of radiant energy from an incident beam."
#> 
#> 
#> $AOD_84
#> $AOD_84$type
#> [1] "RADIATION"
#> 
#> $AOD_84$temporal
#> [1] "HOURLY"
#> 
#> $AOD_84$source
#> [1] "CERES"
#> 
#> $AOD_84$community
#> [1] "AG"
#> 
#> $AOD_84$calculated
#> [1] FALSE
#> 
#> $AOD_84$inputs
#> NULL
#> 
#> $AOD_84$units
#> [1] "dimensionless"
#> 
#> $AOD_84$name
#> [1] "Aerosol Optical Depth 84"
#> 
#> $AOD_84$definition
#> [1] "The optical thickness at 0.84 um measured vertically; the component of the atmosphere to quantify the removal of radiant energy from an incident beam."
#> 
#> 
#> $CLOUD_AMT
#> $CLOUD_AMT$type
#> [1] "RADIATION"
#> 
#> $CLOUD_AMT$temporal
#> [1] "HOURLY"
#> 
#> $CLOUD_AMT$source
#> [1] "CERES"
#> 
#> $CLOUD_AMT$community
#> [1] "AG"
#> 
#> $CLOUD_AMT$calculated
#> [1] FALSE
#> 
#> $CLOUD_AMT$inputs
#> NULL
#> 
#> $CLOUD_AMT$units
#> [1] "%"
#> 
#> $CLOUD_AMT$name
#> [1] "Cloud Amount"
#> 
#> $CLOUD_AMT$definition
#> [1] "The average percent of cloud amount during the temporal period."
#> 
#> 
#> $CLOUD_OD
#> $CLOUD_OD$type
#> [1] "RADIATION"
#> 
#> $CLOUD_OD$temporal
#> [1] "HOURLY"
#> 
#> $CLOUD_OD$source
#> [1] "CERES"
#> 
#> $CLOUD_OD$community
#> [1] "AG"
#> 
#> $CLOUD_OD$calculated
#> [1] FALSE
#> 
#> $CLOUD_OD$inputs
#> NULL
#> 
#> $CLOUD_OD$units
#> [1] "dimensionless"
#> 
#> $CLOUD_OD$name
#> [1] "Cloud Optical Visible Depth"
#> 
#> $CLOUD_OD$definition
#> [1] "The vertical optical thickness between the top and bottom of a cloud."
#> 
#> 
#> $CLRSKY_SFC_LW_DWN
#> $CLRSKY_SFC_LW_DWN$type
#> [1] "RADIATION"
#> 
#> $CLRSKY_SFC_LW_DWN$temporal
#> [1] "HOURLY"
#> 
#> $CLRSKY_SFC_LW_DWN$source
#> [1] "CERES"
#> 
#> $CLRSKY_SFC_LW_DWN$community
#> [1] "AG"
#> 
#> $CLRSKY_SFC_LW_DWN$calculated
#> [1] FALSE
#> 
#> $CLRSKY_SFC_LW_DWN$inputs
#> NULL
#> 
#> $CLRSKY_SFC_LW_DWN$units
#> [1] "W/m^2"
#> 
#> $CLRSKY_SFC_LW_DWN$name
#> [1] "Clear Sky Surface Longwave Downward Irradiance"
#> 
#> $CLRSKY_SFC_LW_DWN$definition
#> [1] "The downward thermal infrared irradiance under clear sky conditions reaching a horizontal plane the surface of the earth. Also known as Horizontal Infrared Radiation Intensity from Sky."
#> 
#> 
#> $CLRSKY_SFC_SW_DIFF
#> $CLRSKY_SFC_SW_DIFF$type
#> [1] "RADIATION"
#> 
#> $CLRSKY_SFC_SW_DIFF$temporal
#> [1] "HOURLY"
#> 
#> $CLRSKY_SFC_SW_DIFF$source
#> [1] "CERES"
#> 
#> $CLRSKY_SFC_SW_DIFF$community
#> [1] "AG"
#> 
#> $CLRSKY_SFC_SW_DIFF$calculated
#> [1] FALSE
#> 
#> $CLRSKY_SFC_SW_DIFF$inputs
#> NULL
#> 
#> $CLRSKY_SFC_SW_DIFF$units
#> [1] "MJ/hr"
#> 
#> $CLRSKY_SFC_SW_DIFF$name
#> [1] "Clear Sky Surface Shortwave Downward Diffuse Horizontal Irradiance"
#> 
#> $CLRSKY_SFC_SW_DIFF$definition
#> [1] "The diffuse (light energy scattered out of the direction of the sun) solar irradiance incident on a horizontal plane at the surface of the earth under clear sky conditions."
#> 
#> 
#> $CLRSKY_SFC_SW_DIRH
#> $CLRSKY_SFC_SW_DIRH$type
#> [1] "RADIATION"
#> 
#> $CLRSKY_SFC_SW_DIRH$temporal
#> [1] "HOURLY"
#> 
#> $CLRSKY_SFC_SW_DIRH$source
#> [1] "CERES"
#> 
#> $CLRSKY_SFC_SW_DIRH$community
#> [1] "AG"
#> 
#> $CLRSKY_SFC_SW_DIRH$calculated
#> [1] FALSE
#> 
#> $CLRSKY_SFC_SW_DIRH$inputs
#> NULL
#> 
#> $CLRSKY_SFC_SW_DIRH$units
#> [1] "MJ/m^2/day"
#> 
#> $CLRSKY_SFC_SW_DIRH$name
#> [1] "Clear Sky Surface Shortwave Direct Horizontal Irradiance"
#> 
#> $CLRSKY_SFC_SW_DIRH$definition
#> [1] "The direct solar irradiance incident on a horizontal plane at the surface of the earth under clear sky conditions."
#> 
#> 
#> $CLRSKY_SFC_SW_DWN
#> $CLRSKY_SFC_SW_DWN$type
#> [1] "RADIATION"
#> 
#> $CLRSKY_SFC_SW_DWN$temporal
#> [1] "HOURLY"
#> 
#> $CLRSKY_SFC_SW_DWN$source
#> [1] "CERES"
#> 
#> $CLRSKY_SFC_SW_DWN$community
#> [1] "AG"
#> 
#> $CLRSKY_SFC_SW_DWN$calculated
#> [1] FALSE
#> 
#> $CLRSKY_SFC_SW_DWN$inputs
#> NULL
#> 
#> $CLRSKY_SFC_SW_DWN$units
#> [1] "MJ/hr"
#> 
#> $CLRSKY_SFC_SW_DWN$name
#> [1] "Clear Sky Surface Shortwave Downward Irradiance"
#> 
#> $CLRSKY_SFC_SW_DWN$definition
#> [1] "The total solar irradiance incident (direct plus diffuse) on a horizontal plane at the surface of the earth under clear sky conditions. An alternative term for the total solar irradiance is the \"Global Horizontal Irradiance\" or GHI."
#> 
#> 
#> $PW
#> $PW$type
#> [1] "RADIATION"
#> 
#> $PW$temporal
#> [1] "HOURLY"
#> 
#> $PW$source
#> [1] "CERES"
#> 
#> $PW$community
#> [1] "AG"
#> 
#> $PW$calculated
#> [1] FALSE
#> 
#> $PW$inputs
#> NULL
#> 
#> $PW$units
#> [1] "cm"
#> 
#> $PW$name
#> [1] "Precipitable Water"
#> 
#> $PW$definition
#> [1] "The total atmospheric water vapor contained in a vertical column of the atmosphere."
#> 
#> 
#> $SZA
#> $SZA$type
#> [1] "RADIATION"
#> 
#> $SZA$temporal
#> [1] "HOURLY"
#> 
#> $SZA$source
#> [1] "CERES"
#> 
#> $SZA$community
#> [1] "AG"
#> 
#> $SZA$calculated
#> [1] FALSE
#> 
#> $SZA$inputs
#> NULL
#> 
#> $SZA$units
#> [1] "Degrees"
#> 
#> $SZA$name
#> [1] "Solar Zenith Angle"
#> 
#> $SZA$definition
#> [1] "The angle between the geodetic zenith vector and a vector from the earth point to the sun integrated over the period."
#> 
#> 
#> $TOA_SW_DWN
#> $TOA_SW_DWN$type
#> [1] "RADIATION"
#> 
#> $TOA_SW_DWN$temporal
#> [1] "HOURLY"
#> 
#> $TOA_SW_DWN$source
#> [1] "CERES"
#> 
#> $TOA_SW_DWN$community
#> [1] "AG"
#> 
#> $TOA_SW_DWN$calculated
#> [1] FALSE
#> 
#> $TOA_SW_DWN$inputs
#> NULL
#> 
#> $TOA_SW_DWN$units
#> [1] "MJ/hr"
#> 
#> $TOA_SW_DWN$name
#> [1] "Top-Of-Atmosphere Shortwave Downward Irradiance"
#> 
#> $TOA_SW_DWN$definition
#> [1] "The total solar irradiance incident (direct plus diffuse) on a horizontal plane at the top of the atmosphere (extraterrestrial radiation)."
#> 
#> 
#> $ALLSKY_KT
#> $ALLSKY_KT$type
#> [1] "RADIATION"
#> 
#> $ALLSKY_KT$temporal
#> [1] "HOURLY"
#> 
#> $ALLSKY_KT$source
#> [1] "POWER"
#> 
#> $ALLSKY_KT$community
#> [1] "AG"
#> 
#> $ALLSKY_KT$calculated
#> [1] FALSE
#> 
#> $ALLSKY_KT$inputs
#> NULL
#> 
#> $ALLSKY_KT$units
#> [1] "dimensionless"
#> 
#> $ALLSKY_KT$name
#> [1] "All Sky Insolation Clearness Index"
#> 
#> $ALLSKY_KT$definition
#> [1] "A fraction representing clearness of the atmosphere; the all sky insolation that is transmitted through the atmosphere to strike the surface of the earth divided by the average of top of the atmosphere total solar irradiance incident."
#> 
#> 
#> $ALLSKY_NKT
#> $ALLSKY_NKT$type
#> [1] "RADIATION"
#> 
#> $ALLSKY_NKT$temporal
#> [1] "HOURLY"
#> 
#> $ALLSKY_NKT$source
#> [1] "POWER"
#> 
#> $ALLSKY_NKT$community
#> [1] "AG"
#> 
#> $ALLSKY_NKT$calculated
#> [1] FALSE
#> 
#> $ALLSKY_NKT$inputs
#> NULL
#> 
#> $ALLSKY_NKT$units
#> [1] "dimensionless"
#> 
#> $ALLSKY_NKT$name
#> [1] "All Sky Normalized Insolation Clearness Index"
#> 
#> $ALLSKY_NKT$definition
#> [1] "The average zenith angle-independent expression of the all sky insolation clearness index."
#> 
#> 
#> $ALLSKY_SFC_PAR_TOT
#> $ALLSKY_SFC_PAR_TOT$type
#> [1] "RADIATION"
#> 
#> $ALLSKY_SFC_PAR_TOT$temporal
#> [1] "HOURLY"
#> 
#> $ALLSKY_SFC_PAR_TOT$source
#> [1] "POWER"
#> 
#> $ALLSKY_SFC_PAR_TOT$community
#> [1] "AG"
#> 
#> $ALLSKY_SFC_PAR_TOT$calculated
#> [1] FALSE
#> 
#> $ALLSKY_SFC_PAR_TOT$inputs
#> NULL
#> 
#> $ALLSKY_SFC_PAR_TOT$units
#> [1] "W/m^2"
#> 
#> $ALLSKY_SFC_PAR_TOT$name
#> [1] "All Sky Surface PAR Total"
#> 
#> $ALLSKY_SFC_PAR_TOT$definition
#> [1] "The total Photosynthetically Active Radiation (PAR) incident on a horizontal plane at the surface of the earth under all sky conditions."
#> 
#> 
#> $ALLSKY_SFC_SW_DNI
#> $ALLSKY_SFC_SW_DNI$type
#> [1] "RADIATION"
#> 
#> $ALLSKY_SFC_SW_DNI$temporal
#> [1] "HOURLY"
#> 
#> $ALLSKY_SFC_SW_DNI$source
#> [1] "POWER"
#> 
#> $ALLSKY_SFC_SW_DNI$community
#> [1] "AG"
#> 
#> $ALLSKY_SFC_SW_DNI$calculated
#> [1] FALSE
#> 
#> $ALLSKY_SFC_SW_DNI$inputs
#> NULL
#> 
#> $ALLSKY_SFC_SW_DNI$units
#> [1] "MJ/hr"
#> 
#> $ALLSKY_SFC_SW_DNI$name
#> [1] "All Sky Surface Shortwave Downward Direct Normal Irradiance"
#> 
#> $ALLSKY_SFC_SW_DNI$definition
#> [1] "The direct solar irradiance incident to a horizontal plane normal (perpendicular) to the direction of the sun's position under all sky conditions."
#> 
#> 
#> $ALLSKY_SRF_ALB
#> $ALLSKY_SRF_ALB$type
#> [1] "RADIATION"
#> 
#> $ALLSKY_SRF_ALB$temporal
#> [1] "HOURLY"
#> 
#> $ALLSKY_SRF_ALB$source
#> [1] "POWER"
#> 
#> $ALLSKY_SRF_ALB$community
#> [1] "AG"
#> 
#> $ALLSKY_SRF_ALB$calculated
#> [1] FALSE
#> 
#> $ALLSKY_SRF_ALB$inputs
#> NULL
#> 
#> $ALLSKY_SRF_ALB$units
#> [1] "dimensionless"
#> 
#> $ALLSKY_SRF_ALB$name
#> [1] "All Sky Surface Albedo"
#> 
#> $ALLSKY_SRF_ALB$definition
#> [1] "The all sky rate of reflectivity of the earth's surface; the ratio of the solar energy reflected by the surface of the earth compared to the total solar energy incident reaching the surface of the earth."
#> 
#> 
#> $CLRSKY_KT
#> $CLRSKY_KT$type
#> [1] "RADIATION"
#> 
#> $CLRSKY_KT$temporal
#> [1] "HOURLY"
#> 
#> $CLRSKY_KT$source
#> [1] "POWER"
#> 
#> $CLRSKY_KT$community
#> [1] "AG"
#> 
#> $CLRSKY_KT$calculated
#> [1] FALSE
#> 
#> $CLRSKY_KT$inputs
#> NULL
#> 
#> $CLRSKY_KT$units
#> [1] "dimensionless"
#> 
#> $CLRSKY_KT$name
#> [1] "Clear Sky Insolation Clearness Index"
#> 
#> $CLRSKY_KT$definition
#> [1] "A fraction representing clearness of the atmosphere; the clear sky insolation that is transmitted through the atmosphere to strike the surface of the earth divided by the average of top of the atmosphere total solar irradiance incident."
#> 
#> 
#> $CLRSKY_NKT
#> $CLRSKY_NKT$type
#> [1] "RADIATION"
#> 
#> $CLRSKY_NKT$temporal
#> [1] "HOURLY"
#> 
#> $CLRSKY_NKT$source
#> [1] "POWER"
#> 
#> $CLRSKY_NKT$community
#> [1] "AG"
#> 
#> $CLRSKY_NKT$calculated
#> [1] FALSE
#> 
#> $CLRSKY_NKT$inputs
#> NULL
#> 
#> $CLRSKY_NKT$units
#> [1] "dimensionless"
#> 
#> $CLRSKY_NKT$name
#> [1] "Clear Sky Normalized Insolation Clearness Index"
#> 
#> $CLRSKY_NKT$definition
#> [1] "The average zenith angle-independent expression of the clear sky insolation clearness index."
#> 
#> 
#> $CLRSKY_SFC_PAR_TOT
#> $CLRSKY_SFC_PAR_TOT$type
#> [1] "RADIATION"
#> 
#> $CLRSKY_SFC_PAR_TOT$temporal
#> [1] "HOURLY"
#> 
#> $CLRSKY_SFC_PAR_TOT$source
#> [1] "POWER"
#> 
#> $CLRSKY_SFC_PAR_TOT$community
#> [1] "AG"
#> 
#> $CLRSKY_SFC_PAR_TOT$calculated
#> [1] FALSE
#> 
#> $CLRSKY_SFC_PAR_TOT$inputs
#> NULL
#> 
#> $CLRSKY_SFC_PAR_TOT$units
#> [1] "W/m^2"
#> 
#> $CLRSKY_SFC_PAR_TOT$name
#> [1] "Clear Sky Surface PAR Total"
#> 
#> $CLRSKY_SFC_PAR_TOT$definition
#> [1] "The total Photosynthetically Active Radiation (PAR) incident on a horizontal plane at the surface of the earth under clear sky conditions."
#> 
#> 
#> $CLRSKY_SFC_SW_DNI
#> $CLRSKY_SFC_SW_DNI$type
#> [1] "RADIATION"
#> 
#> $CLRSKY_SFC_SW_DNI$temporal
#> [1] "HOURLY"
#> 
#> $CLRSKY_SFC_SW_DNI$source
#> [1] "POWER"
#> 
#> $CLRSKY_SFC_SW_DNI$community
#> [1] "AG"
#> 
#> $CLRSKY_SFC_SW_DNI$calculated
#> [1] FALSE
#> 
#> $CLRSKY_SFC_SW_DNI$inputs
#> NULL
#> 
#> $CLRSKY_SFC_SW_DNI$units
#> [1] "MJ/hr"
#> 
#> $CLRSKY_SFC_SW_DNI$name
#> [1] "Clear Sky Surface Shortwave Downward Direct Normal Irradiance"
#> 
#> $CLRSKY_SFC_SW_DNI$definition
#> [1] "The direct solar irradiance incident to a horizontal plane normal (perpendicular) to the direction of the sun's position under clear sky conditions."
#> 
#> 
#> $CLRSKY_SRF_ALB
#> $CLRSKY_SRF_ALB$type
#> [1] "RADIATION"
#> 
#> $CLRSKY_SRF_ALB$temporal
#> [1] "HOURLY"
#> 
#> $CLRSKY_SRF_ALB$source
#> [1] "POWER"
#> 
#> $CLRSKY_SRF_ALB$community
#> [1] "AG"
#> 
#> $CLRSKY_SRF_ALB$calculated
#> [1] FALSE
#> 
#> $CLRSKY_SRF_ALB$inputs
#> NULL
#> 
#> $CLRSKY_SRF_ALB$units
#> [1] "dimensionless"
#> 
#> $CLRSKY_SRF_ALB$name
#> [1] "Clear Sky Surface Albedo"
#> 
#> $CLRSKY_SRF_ALB$definition
#> [1] "The clear sky rate of reflectivity of the earth's surface; the ratio of the solar energy reflected by the surface of the earth compared to the total solar energy incident reaching the surface of the earth."
#> 
#> 
#> $DIFFUSE_ILLUMINANCE
#> $DIFFUSE_ILLUMINANCE$type
#> [1] "RADIATION"
#> 
#> $DIFFUSE_ILLUMINANCE$temporal
#> [1] "HOURLY"
#> 
#> $DIFFUSE_ILLUMINANCE$source
#> [1] "POWER"
#> 
#> $DIFFUSE_ILLUMINANCE$community
#> [1] "AG"
#> 
#> $DIFFUSE_ILLUMINANCE$calculated
#> [1] FALSE
#> 
#> $DIFFUSE_ILLUMINANCE$inputs
#> NULL
#> 
#> $DIFFUSE_ILLUMINANCE$units
#> [1] "lux"
#> 
#> $DIFFUSE_ILLUMINANCE$name
#> [1] "Diffuse Illuminance"
#> 
#> $DIFFUSE_ILLUMINANCE$definition
#> [1] "The average amount of illuminance received directly from the solar disk on a surface perpendicular to the suns rays."
#> 
#> 
#> $DIRECT_ILLUMINANCE
#> $DIRECT_ILLUMINANCE$type
#> [1] "RADIATION"
#> 
#> $DIRECT_ILLUMINANCE$temporal
#> [1] "HOURLY"
#> 
#> $DIRECT_ILLUMINANCE$source
#> [1] "POWER"
#> 
#> $DIRECT_ILLUMINANCE$community
#> [1] "AG"
#> 
#> $DIRECT_ILLUMINANCE$calculated
#> [1] FALSE
#> 
#> $DIRECT_ILLUMINANCE$inputs
#> NULL
#> 
#> $DIRECT_ILLUMINANCE$units
#> [1] "lux"
#> 
#> $DIRECT_ILLUMINANCE$name
#> [1] "Direct Illuminance"
#> 
#> $DIRECT_ILLUMINANCE$definition
#> [1] "The average amount of illuminance received from the sky (excluding the solar disk) on a horizontal plane."
#> 
#> 
#> $GLOBAL_ILLUMINANCE
#> $GLOBAL_ILLUMINANCE$type
#> [1] "RADIATION"
#> 
#> $GLOBAL_ILLUMINANCE$temporal
#> [1] "HOURLY"
#> 
#> $GLOBAL_ILLUMINANCE$source
#> [1] "POWER"
#> 
#> $GLOBAL_ILLUMINANCE$community
#> [1] "AG"
#> 
#> $GLOBAL_ILLUMINANCE$calculated
#> [1] FALSE
#> 
#> $GLOBAL_ILLUMINANCE$inputs
#> NULL
#> 
#> $GLOBAL_ILLUMINANCE$units
#> [1] "lux"
#> 
#> $GLOBAL_ILLUMINANCE$name
#> [1] "Global Illuminance"
#> 
#> $GLOBAL_ILLUMINANCE$definition
#> [1] "The average total amount of direct and diffuse illuminance on a horizontal plane."
#> 
#> 
#> $TOA_SW_DNI
#> $TOA_SW_DNI$type
#> [1] "RADIATION"
#> 
#> $TOA_SW_DNI$temporal
#> [1] "HOURLY"
#> 
#> $TOA_SW_DNI$source
#> [1] "POWER"
#> 
#> $TOA_SW_DNI$community
#> [1] "AG"
#> 
#> $TOA_SW_DNI$calculated
#> [1] FALSE
#> 
#> $TOA_SW_DNI$inputs
#> NULL
#> 
#> $TOA_SW_DNI$units
#> [1] "MJ/hr"
#> 
#> $TOA_SW_DNI$name
#> [1] "Top-Of-Atmosphere Shortwave Direct Normal Radiation"
#> 
#> $TOA_SW_DNI$definition
#> [1] "The total solar irradiance incident (direct plus diffuse) on a horizontal plane where oriented to the sun's position at the top of the atmosphere (extraterrestrial radiation)."
#> 
#> 
#> $ZENITH_LUMINANCE
#> $ZENITH_LUMINANCE$type
#> [1] "RADIATION"
#> 
#> $ZENITH_LUMINANCE$temporal
#> [1] "HOURLY"
#> 
#> $ZENITH_LUMINANCE$source
#> [1] "POWER"
#> 
#> $ZENITH_LUMINANCE$community
#> [1] "AG"
#> 
#> $ZENITH_LUMINANCE$calculated
#> [1] FALSE
#> 
#> $ZENITH_LUMINANCE$inputs
#> NULL
#> 
#> $ZENITH_LUMINANCE$units
#> [1] "cd/m^2"
#> 
#> $ZENITH_LUMINANCE$name
#> [1] "Zenith luminance"
#> 
#> $ZENITH_LUMINANCE$definition
#> [1] "The average amount of luminance at the skys zenith."
```

## A Note on API Throttling

The POWER API endpoints limit queries to prevent overloads due to repetitive and rapid requests.
If you find that the API is throttling your queries, I suggest that you investigate the use of `limit_rate()` from [_ratelimitr_](https://cran.r-project.org/package=ratelimitr) to create self-limiting functions that will respect the rate limits that the API has in place.
It is best to check the [POWER website](https://power.larc.nasa.gov/docs/services/api/#rate-limiting) for the latest rate limits as they differ between temporal APIs and may change over time as the project matures.

## References

<https://power.larc.nasa.gov>

<https://power.larc.nasa.gov/docs/methodology/>
